apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-svcmysql8 # nome do meu service
spec:
    ports:
        - port: 3306 # porta de entrada do meu service - fica do lado cliente
          targetPort: 3306 # porta de saída do meu service - aponta para o pod backend
          protocol: TCP
    selector:
        app: {{ .Release.Name }}-mysql8 #nome do meu deployment
