apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-svc-voll-med-api
spec:
    selector:
        app: {{ .Release.Name }}-voll-med-api # seleciona pod do deplyment
    ports:
        - port: 8081
          targetPort: 8081
          protocol: TCP
    type: {{ .Values.api.serviceType }}
