apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Release.Name }}-voll-med-api # nomed do deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: {{ .Release.Name }}-voll-med-api # nome para referenciar o deployment e pods
    template:
        metadata:
            labels:
                app: {{ .Release.Name }}-voll-med-api # nome que outros serviços usuarão para falar com os pods
        spec:
            containers:
                - name: voll-med-api
                  image: {{ .Values.api.image }}
                  imagePullPolicy: IfNotPresent # para baixar do dockerhub caso nao exista na máquina local
                  resources:
                      limits:
                          memory: "500Mi"
                          cpu: "500m"
                  ports:
                      - containerPort: 8081
                  env:
                      - name: MYSQL_URL # nome da variável esperada
                        value: {{ .Values.mysql8.url }}
                      - name: MYSQL_USER # nome da variável esperada
                        value: {{ .Values.mysql8.user }}
                      - name: MYSQL_PASSWORD # nome da variável esperada
                        value: {{ .Values.mysql8.password }}