mysql8:
    image: mysql:8
    tag: 8
    user: user
    password: pass
    root_password: pass
    database: vollmed_api
    url: jdbc:mysql://apivollmed-svcmysql8:3306/vollmed_api
api:
    ingress:
        enabled: true
        hosts: [apimedicos.cryss.dev, api.medicos, medicos.com]
    image: cryssantos9/api.med.voll:v3 # imagem no docker hub
    serviceType: ClusterIP
